# Generated by Django 4.0.1 on 2022-05-25 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=30, verbose_name='Asset name ')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Job Title')),
                ('origin', models.CharField(max_length=150, verbose_name='Job Origin')),
                ('destination', models.CharField(max_length=150, verbose_name='Job Destination')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Tracker latitude value')),
                ('lng', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Tracker longitude value')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='unread', max_length=264, null=True)),
                ('type_of_notification', models.CharField(blank=True, max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(max_length=30, verbose_name='Tracker name ')),
                ('status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.asset', verbose_name='related Asset')),
            ],
        ),
    ]
