# Generated by Django 4.0.1 on 2022-05-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='tracker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.tracker', verbose_name='related tracker'),
            preserve_default=False,
        ),
    ]
