# Generated by Django 4.0.1 on 2022-05-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
