# Generated by Django 4.0.1 on 2022-05-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracking.tracker', verbose_name='Assigned Tracker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=30, verbose_name='Asset name '),
        ),
    ]
