# Generated by Django 4.0.1 on 2022-05-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_asset_assigned_tracker_alter_asset_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='tracker_name',
            field=models.CharField(default='None', max_length=30, verbose_name='Tracker name '),
            preserve_default=False,
        ),
    ]
