# Generated by Django 4.0.1 on 2022-05-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_alter_asset_assigned_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assigned_tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.tracker', verbose_name='Assigned Tracker'),
        ),
    ]
