# Generated by Django 4.0.1 on 2022-05-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Total Distance Covered')),
                ('maintenance_status', models.CharField(default='Pending', max_length=10)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.location')),
            ],
        ),
    ]
