# Generated by Django 4.0.1 on 2022-05-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_delete_user'),
        ('maintenance', '0003_alter_maintenance_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.tracker', verbose_name='related tracker'),
        ),
    ]
