# Generated by Django 4.0.1 on 2022-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenance_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='description',
            field=models.CharField(default='CHANGE OIL', max_length=100),
        ),
    ]
