# Generated by Django 4.0.1 on 2022-05-24 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_limit',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_status',
            field=models.CharField(default='Not Pending', max_length=15),
        ),
    ]
