# Generated by Django 4.0.1 on 2022-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenance_maintenance_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.CharField(default='NO MAINTENANCE SCHEDULE', max_length=100),
        ),
    ]
